config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/login' => 'sessions#new', as: :login
  post '/sessions/new' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  get '/home' => 'users#home', as: :home
  get '/reminder' => 'users#send_reminder', as: :send_reminder

  resources :users, only: [:new, :create, :edit, :update] do
    resources :questions, only: [:new, :create, :show, :edit, :update]
    member do
      get 'answer'
      post 'add_answers'
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  has_one    :user, through: :question
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user
  has_many   :answers

  accepts_nested_attributes_for :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt
  has_many :questions
  has_many :answers, through: :questions

  has_secure_password

  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :answers

  validates :password, confirmation: true
  # validates :password_confirmation, presence: true

  def self.send_daily_emails
    @users = find_users_that_want_emails_now
  end

  def set_defaults
    self.update(
      send_time: Time.new(2000,1,1,21),
      sunday: true,
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true)
  end

  def find_users_that_want_emails_now
    today = Time.now
    time = today.floor(15.minutes)

    case today.wday
    when 0
      User.where(sunday: true).where('send_time = ?', time)

    end
  end

  def floor(seconds = 60)
    Time.at((self.to_f / seconds).floor * seconds)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    session[:user_id] && session[:expires_on] > Time.now
  end
  helper_method :logged_in?

  def authenticate
    redirect_to login_path unless logged_in?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate

  def new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to home_path
    else
      render 'new'
    end
  end

  def show
    @question = Question.find_by_id(params[:id])
    @answers = @question.answers
  end

  def edit
    @question = Question.find_by_id(params[:id])
  end

  def update
    @question = Question.find_by_id(params[:id])

    if @question.update(question_params)
      redirect_to user_question_path(current_user, @question)
    else
      #TODO catch errors
      render 'edit'
    end
  end

  private
    def question_params
      params.require(:question).permit(:text,:answer_type)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id

      params[:user][:remember_me] ? exp = Time.now + 1.year : exp = Time.now + 1.hours
      session[:expires_on] = exp

      redirect_to home_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]

  def home
    @questions = current_user.questions.order(:created_at)
  end

  def new
    @user = User.new
  end

  def edit
    @time = current_user.send_time
    @days_of_week = [:sunday,:monday,:tuesday,:wednesday,:thursday,:friday,:saturday]
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.set_defaults
      session[:user_id] = @user.id

      params[:user][:remember_me] ? exp = Time.now + 1.year : exp = Time.now + 1.hours
      session[:expires_on] = exp

      UserMailer.welcome_email(@user).deliver
      redirect_to home_path
    else
      render 'new'
    end
  end

  def update
    p user_update_params
    if current_user.update(user_update_params)
      redirect_to home_path
    else
      #TODO catch errors
      @days_of_week = [:sunday,:monday,:tuesday,:wednesday,:thursday,:friday,:saturday]
      render 'edit'
    end
  end

  def answer
    @questions = current_user.questions.order(:created_at)
  end

  def add_answers
    date_hash = params[:answers].delete('date')
    date = find_answer_for_date(date_hash)

    params[:answers].each do |answer|
      question = Question.find_by_id(answer[0])
      if !question.answers.create(value: answer[1], answer_for: date)
        #TODO catch errors
        render 'answer'
      end
    end
    #TODO show message that answers were save successfully
    redirect_to home_path
  end

  def send_reminder
    #TODO if we are going to keep this make it visible to user that message was sent
    UserMailer.daily_reminder(current_user).deliver
    redirect_to :back
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :cell, :password, :password_confirmation)
    end

    def user_update_params
      params.require(:user).permit(:send_time,:monday,:tuesday,:wednesday,:thursday,:friday,:saturday,:sunday)
    end

    def find_answer_for_date(date_hash)
      Date.civil(date_hash['date(1i)'].to_i,
                 date_hash['date(2i)'].to_i,
                 date_hash['date(3i)'].to_i)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<tr>
  <td><%= answer.answer_for.strftime("%a %b %d") %></td>
  <td><%= answer.value %></td>
</tr>

app/views/application/_navbar.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <h5 class="navbar-text">Welcome, <%= current_user.username %></h5>
        </li>
        <li>
          <h5 class="navbar-text"><%= link_to 'Homepage', home_path %></h5>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <h5 class="navbar-text"><%= link_to 'Logout', logout_path, method: 'delete' %></h5>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyDailyInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'navbar', layout: false %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for :question, url: "/users/#{current_user.id}/questions" do |f| %>
  <p>
    <%= f.label "What should we ask you?" %>
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.label "What type of answer?" %>
    <%= f.select :answer_type, [['Numeric','number_field'],['A few words','text_field'],['A lot of words','text_area']] %>
  </p>
  <p>
    <%= f.submit value = "Add new daily question" %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<li><h4><%= link_to question.text, user_question_path(current_user, question) %></h4></li>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for :question, url: "/users/#{current_user.id}/questions/#{@question.id}", method: 'put' do |f| %>
  <p>
    <%= f.label "What should we ask you?" %>
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.label "What type of answer?" %>
    <%= f.select :answer_type, [['Numeric','number_field'],['A few words','text_field'],['A lot of words','text_area']] %>
  </p>
  <p>
    <%= f.submit value = "Update question" %>
  </p>
<% end %>

<%= button_to "Cancel", user_question_path(current_user, @question), method: 'get' %>

app/views/questions/new.html.erb
<h1>Add a new question to the list</h1>

<%= render 'form' %>

<%= button_to "Back", home_path, method: 'get' %>

app/views/questions/show.html.erb
<h4>Question Detail page: </h4>

<h1><%= @question.text %></h1>
<p>
  <%= button_to "Edit", edit_user_question_path(current_user, @question), method: 'get' %>
</p>

<h3>Recent Answers</h3>

<% if @answers.length > 0 %>
  <table class="table">
    <th>Date</th>
    <th>Value</th>
      <%= render @answers %>
  </table>
<% else %>
  <h5>You've never answered this question!</h5>
<% end %>

<%= button_to "Back", home_path, method: 'get' %>

app/views/users/_form.html.erb
<%= form_for :user, url: '/users', method: 'post' do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :cell %>
    <%= f.text_field :cell %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :stay_logged_in %>
    <%= check_box_tag :remember_me %>
  <p>
    <%= f.submit value="Create account" %>
<% end %>

app/views/users/answer.html.erb
<%= form_for :answers, url: "/users/#{session[:user_id]}/add_answers" do |f| %>
  <%= f.fields_for :date do |date_form| %>
    <h4>Answers for:
    <%= date_form.date_select(:date) %></h4><br>
  <% end %>

  <% @questions.each do |question| %>
    <p>
      <%= f.label question.text %>
      <%= f.text_field question.id %>
    </p>
  <% end %>
  <%= f.submit value = "Save Answers" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Reminder Preferences</h1>

<%= form_for :user, url: "/users/#{current_user.id}", method: 'put' do |f| %>
  <p>
    <%= f.label "What time should we email you?" %>
    <%= f.time_select(:send_time, {ampm: true, minute_step: 10}) %>
  </p>
  <p>
    <% @days_of_week.each do |day| %>
      <%= f.check_box day %>
      <%= f.label day %><br>
    <% end %>
  </p>
  <p>
    <%= f.submit value = "update preferences" %>
  </p>
<% end %>

app/views/users/home.html.erb
<%= button_to "Submit answers", answer_user_path(current_user), method: 'get' %>
<%= link_to "Edit preferences", edit_user_path(current_user) %><br>

<br>
<div id="question list">
  <h3>Your set of daily questions</h3>
  <ul>
    <%= render @questions %>
  </ul>
</div>
<br>

<%= button_to "Add a new question", new_user_question_path(current_user), method: 'get' %>

<%= link_to "send reminder email now", send_reminder_path(current_user) %>

app/views/users/new.html.erb
<h1>Welcome!</h1>

<%= render 'form' %>